### ISSUE TITLE
Phased genotype in VCF?

### ISSUE THREAD

**Issue by hsiehph** [eldariont/svim-asm#12]
Hello,

Not sure if I miss this, but I am wondering if it is safe to assume that the genotypes reported in the output VCF are phased.  I am using v1.0.2 with the diploid mode and only saw the unphased "/", not the phased "|" delimiter in the VCF.  More specifically, if the input BAM1 and BAM2 provided correspond to perfectly phased haplotypes H1 and H2 of my sample, are the 1st and 2nd alleles always from H1/BAM1 and H2/BAM2, respectively? 

Thanks,
PingHsun(Benson)

**Comment by jakob-he** [comment]
Hi PingHsun,

thank you for your interest in SVIM-asm and I apologize that I haven't responded earlier to your question. 
If you use the diploid mode of SVIM-asm and provide two perfectly phased haplotypes it reports a phased genotype.
Briefly, SVIM-asm first compares the aligned haplotypes to a reference and calls structural variants for each. Then the calls are "paired" and genotyped i.e. if a variant is present in one haplotype the genotype is set to 0/1 or 1/0 (depending on which haplotype contains the variant) and to 1/1 if the variant is present in both haplotypes.

Still, you are correct that the delimiter is not indicating a phased genotype. We will definitely get back to this in a future update of SVIM-asm.

Best,
Jakob

**Comment by hsiehph** [comment]
Thanks for the answer!
