### ISSUE TITLE
MAF alignments format

### ISSUE THREAD

**Issue by biozzq** [eldariont/svim-asm#3]
Dear all
Can we use one-to-one MAF alignments (the alignment was generated by LAST) format to identify structural rearrangements? 
Best,
zheng zhuqing

**Comment by eldariont** [comment]
Hi Zheng,

SVIM-asm requires input alignments to be in SAM/BAM format. However, you could try to convert MAF to SAM with a tool, such as [maf-convert](http://last.cbrc.jp/doc/maf-convert.html) (included in LAST).

Best,
David
