### ISSUE TITLE
svim-asm for bacterial genome

### ISSUE THREAD

**Issue by rthapa1** [eldariont/svim-asm#4]
Can svim-asm be used to call structural variants Fromm bacterial genome?

**Comment by eldariont** [comment]
Hi,

thanks for the question. In principle, svim-asm should work on a bacterial genome. You probably want to use the haploid mode (`svim-asm haploid`) for comparing two bacterial genomes.

After you have tried it, I'd be interested to read how the results look like and whether they were what you expected.

Cheers
David
