### ISSUE TITLE
-r2k

### ISSUE THREAD

**Issue by atongsa** [eldariont/svim-asm#7]
what is the meaning of -r2k in the sample code

```
minimap2 -a -x asm10 --cs -r2k
```

**Comment by eldariont** [comment]
Hi,

thanks for the question. From the minimap2 documentation:

```
-r INT    Bandwidth used in chaining and DP-based alignment [500]. This option approximately controls the maximum gap size.
```

So `-r2k` sets the bandwidth to 2000 bases which improves long Indel alignment. See for instance [here](https://github.com/lh3/minimap2/issues/341#issuecomment-466502467).

Cheers
David
