### ISSUE TITLE
error: CIGAR length too long at position 1

### ISSUE THREAD

**Issue by atongsa** [eldariont/svim-asm#8]
i get this error from 

```
minimap2 -a -x asm10  --cs -r2k -t $n_thr $ref_fa $query_fa > o.sam
samtools sort  o.sam

```

may i add the -L option in minimap2 to solve the problem

**Comment by eldariont** [comment]
Hi,

sure, the `-L` option solves some problems with long CIGAR strings so you can try. If problems persist you might want to contact the developers of samtools or minimap2 as this is not a SVIM-asm issue as far as I can tell.

Best
David

**Comment by WimSpee** [comment]
Or maybe a SAM reader could be add to SVIM-ASM? This for example has been done in Syri. 
https://github.com/schneebergerlab/syri

**Comment by WimSpee** [comment]
CRAM also seems to not have this issue. 
https://github.com/lh3/minimap2/issues/16

**Comment by WimSpee** [comment]
@eldariont Could you please have a look if it is possible to have SVIM-ASM read in SAM or CRAM files to fix the "too long CIGAR" issue?
See also the above comments and links.  

Thank you.
